In [2]:
import torch
print(torch.__version__)

2.10.0


In [7]:
if torch.cuda.is_available():
    print("CUDA is available. You can use GPU acceleration.")

if torch.backends.mps.is_available():
    print("MPS (Metal Performance Shaders) is available. You can use GPU acceleration on macOS.")

else:
    print("MPS (Metal Performance Shaders) is not available. You may not be able to use GPU acceleration on macOS.")

MPS (Metal Performance Shaders) is available. You can use GPU acceleration on macOS.


# Creating a tensor

In [10]:
a = torch.empty(2,3)

In [11]:
type(a)

torch.Tensor

In [12]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [17]:
torch.rand(2,3)

tensor([[0.7155, 0.8715, 0.8177],
        [0.8974, 0.6711, 0.7683]])

In [18]:
torch.manual_seed(42)  # Set a random seed for reproducibility

In [19]:
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [21]:
torch.manual_seed(42)  # Set a random seed for reproducibility
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [23]:
b = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [27]:
type(b)

torch.Tensor

# Tensor data type

In [30]:
b = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [31]:
b.dtype

torch.int64

In [34]:
torch.tensor([1.0, 2.0, 3.0],
              dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [35]:
b.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| Data Type             | Dtype         | Description                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 32-bit Floating Point | torch.float32   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| 64-bit Floating Point | torch.float64   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| 16-bit Floating Point | torch.float16   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| BFloat16              | torch.bfloat16  | Brain floating-point format with reduced precision compared to float16. Used in mixed-precision training, especially on TPUs.                                                |
| 8-bit Floating Point  | torch.float8    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| 8-bit Integer         | torch.int8      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| 16-bit Integer        | torch.int16     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| 32-bit Integer        | torch.int32     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| 64-bit Integer        | torch.int64     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| 8-bit Unsigned Integer| torch.uint8     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| Boolean               | torch.bool      | Boolean type, stores True or False values. Often used for masks in logical operations.                                                                                      |
| Complex 64            | torch.complex64 | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| Complex 128           | torch.complex128| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| Quantized Integer     | torch.qint8     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| Quantized Unsigned Integer | torch.quint8 | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |

In [37]:
x = torch.rand(2, 3)
x

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

In [38]:
print(x.shape)  # Output: torch.Size([2, 3])

torch.Size([2, 3])


In [39]:
x + 2

tensor([[2.8694, 2.5677, 2.7411],
        [2.4294, 2.8854, 2.5739]])

In [40]:
x - 2

tensor([[-1.1306, -1.4323, -1.2589],
        [-1.5706, -1.1146, -1.4261]])

In [41]:
x * 2

tensor([[1.7388, 1.1354, 1.4822],
        [0.8588, 1.7709, 1.1478]])

In [42]:
x / 2

tensor([[0.4347, 0.2839, 0.3705],
        [0.2147, 0.4427, 0.2870]])

In [43]:
# x mod
x % 2

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

# Element wise operation

In [45]:
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])

print(a)
print(b)
  # Element-wise addition

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])


#### item wise addition

In [46]:
a + b

tensor([[ 8, 10, 12],
        [14, 16, 18]])

In [47]:
a - b

tensor([[-6, -6, -6],
        [-6, -6, -6]])

In [48]:
a * b

tensor([[ 7, 16, 27],
        [40, 55, 72]])

In [50]:
a ** b

tensor([[         1,        256,      19683],
        [   1048576,   48828125, 2176782336]])

In [49]:
a / b

tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])

In [52]:
# abs
c = torch.tensor([-1, -2, -3])
print(torch.abs(c))

tensor([1, 2, 3])


In [53]:
# negative
d = torch.tensor([1, -2, 3])
print(torch.neg(d))

tensor([-1,  2, -3])


In [54]:
# round
e = torch.tensor([1.2, 2.5, 3.7])
print(torch.round(e))

tensor([1., 2., 4.])


In [55]:
# ceil
f = torch.tensor([1.2, 2.5, 3.7])
print(torch.ceil(f))

tensor([2., 3., 4.])


In [56]:
torch.floor(f)

tensor([1., 2., 3.])

In [57]:
# matrix multiplication
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
c = torch.matmul(a, b)
print(c)


tensor([[19, 22],
        [43, 50]])


# Spexial FUnction


In [68]:
x= torch.tensor([[1, 2, -3], [4, 5, 6]], dtype=torch.float32)
x

tensor([[ 1.,  2., -3.],
        [ 4.,  5.,  6.]])

In [69]:
torch.log(x)

tensor([[0.0000, 0.6931,    nan],
        [1.3863, 1.6094, 1.7918]])

In [70]:
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 4.9787e-02],
        [5.4598e+01, 1.4841e+02, 4.0343e+02]])

In [71]:
# sqrt
print(torch.sqrt(x))
#sigmoid
print(torch.sigmoid(x))
#softmax
print(torch.softmax(x, dim=1))  
#relu
print(torch.relu(x))

tensor([[1.0000, 1.4142,    nan],
        [2.0000, 2.2361, 2.4495]])
tensor([[0.7311, 0.8808, 0.0474],
        [0.9820, 0.9933, 0.9975]])
tensor([[0.2676, 0.7275, 0.0049],
        [0.0900, 0.2447, 0.6652]])
tensor([[1., 2., 0.],
        [4., 5., 6.]])


### Copy tensor

In [79]:
a = torch.tensor([[1,1,3],[4,5,6]])

In [80]:
a

tensor([[1, 1, 3],
        [4, 5, 6]])

In [81]:
b = a

In [82]:
b

tensor([[1, 1, 3],
        [4, 5, 6]])

In [84]:
a[0,0]=6
a

tensor([[6, 1, 3],
        [4, 5, 6]])

In [85]:
b

tensor([[6, 1, 3],
        [4, 5, 6]])

In [86]:
id(a)


13585608400

In [87]:
id(b)

13585608400

In [88]:
b = a.clone()

In [89]:
a

tensor([[6, 1, 3],
        [4, 5, 6]])

In [90]:
b

tensor([[6, 1, 3],
        [4, 5, 6]])

In [91]:
a[0, 0] = 10

In [92]:
a

tensor([[10,  1,  3],
        [ 4,  5,  6]])

In [93]:
b

tensor([[6, 1, 3],
        [4, 5, 6]])

In [94]:
torch.cuda.is_available()

False

In [95]:
torch.mps.is_available()

True

In [96]:
def check_cuda_mps_availability():
    cuda_available = torch.cuda.is_available()
    mps_available = torch.backends.mps.is_available()

    if cuda_available:
        print("CUDA is available. You can use GPU acceleration.")
    else:
        print("CUDA is not available. You may not be able to use GPU acceleration.")

    if mps_available:
        print("MPS (Metal Performance Shaders) is available. You can use GPU acceleration on macOS.")
    else:
        print("MPS (Metal Performance Shaders) is not available. You may not be able to use GPU acceleration on macOS.")

In [97]:
device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
print(f"Using device: {device}")

Using device: mps


In [99]:
torch.rand(2,3, device=device)

tensor([[0.8172, 0.5881, 0.5581],
        [0.7691, 0.3394, 0.4560]], device='mps:0')

In [2]:
import torch
import time
size = 10000
matrix1 = torch.rand(size, size)
matrix2 = torch.rand(size, size)
# measuring the time taken for matrix multiplication on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix1, matrix2)
cpu_time = time.time() - start_time
print(f"Time taken for matrix multiplication on CPU: {cpu_time:.6f} seconds")



# measuring the time taken for matrix multiplication on MPS (if available)
if torch.backends.mps.is_available():
    matrix1_mps = matrix1.to('mps')
    matrix2_mps = matrix2.to('mps')
    start_time = time.time()
    result_mps = torch.matmul(matrix1_mps, matrix2_mps)
    mps_time = time.time() - start_time
    print(f"Time taken for matrix multiplication on MPS: {mps_time:.6f} seconds")

Time taken for matrix multiplication on CPU: 0.733931 seconds
Time taken for matrix multiplication on MPS: 0.000263 seconds


# Reshaping

In [4]:
a = torch.tensor([[1,2,3,22],[4,5,6,23]])
a


tensor([[ 1,  2,  3, 22],
        [ 4,  5,  6, 23]])

In [5]:
a.shape

torch.Size([2, 4])

In [10]:
a.reshape(2,2,2)

tensor([[[ 1,  2],
         [ 3, 22]],

        [[ 4,  5],
         [ 6, 23]]])

In [12]:
a.flatten()

tensor([ 1,  2,  3, 22,  4,  5,  6, 23])

In [15]:
a
a.shape

torch.Size([2, 4])

In [16]:
a.permute(1,0)
print(a.permute(1,0).shape)  # Output: torch.Size([4, 2])

torch.Size([4, 2])


In [22]:
a = torch.rand(226,226,3)
a.shape

torch.Size([226, 226, 3])

In [23]:
# unsqueeze
a.unsqueeze(0).shape  # Output: torch.Size([1, 2, 3])

torch.Size([1, 226, 226, 3])

In [26]:
a.shape

torch.Size([226, 226, 3])

In [29]:
# squeeze
b = torch.rand(1,3)
b.squeeze(0).shape  # Output: torch.Size([3])

torch.Size([3])

## NumPy and Pytorch

In [30]:
import numpy as np

In [31]:
a = torch.tensor([[1,2,3],[4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [34]:
b = a.numpy()
b

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
c = torch.from_numpy(b)

In [37]:
c

tensor([[1, 2, 3],
        [4, 5, 6]])